# Generated by Django 5.2.1 on 2025-07-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0002_perfilusuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='pais',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='biografia',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='carrera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tema_preferido',
            field=models.CharField(choices=[('claro', 'Tema Claro'), ('oscuro', 'Tema Oscuro')], default='claro', max_length=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='universidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
