# Generated by Django 5.2.1 on 2025-07-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0004_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoanimo',
            name='nivel',
            field=models.IntegerField(choices=[(5, 'Muy Bien'), (4, 'Bien'), (3, 'Regular'), (2, 'Mal'), (1, 'Muy Mal')], default=3),
        ),
    ]
