# Generated by Django 5.2.1 on 2025-07-23 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0005_estadoanimo_nivel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesor', models.CharField(blank=True, max_length=100)),
                ('horario', models.CharField(blank=True, help_text='Ejemplo: Lunes y Miércoles 10:00-12:00', max_length=200)),
                ('color', models.CharField(default='#3788d8', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('prioridad', models.CharField(choices=[('alta', '🔴 Alta'), ('media', '🟡 Media'), ('baja', '🟢 Baja')], default='media', max_length=5)),
                ('completada', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyflow.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_entrega'],
            },
        ),
    ]
