# Generated by Django 5.2.2 on 2025-07-23 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0007_gasto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('materiales', 'Materiales de Estudio'), ('libros', 'Libros'), ('tecnologia', 'Tecnología'), ('transporte', 'Transporte'), ('Entretenimiento', 'Entretenimiento'), ('otros', 'Otros')], max_length=20),
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('alerta_porcentaje', models.IntegerField(default=80)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
