# Generated by Django 5.2.2 on 2025-07-23 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0008_alter_gasto_categoria_presupuesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ambiente', models.CharField(choices=[('biblioteca', '📚 Biblioteca'), ('casa', '🏠 Casa'), ('cafe', '☕ Café'), ('universidad', '🏛️ Universidad'), ('otro', '📍 Otro')], max_length=20)),
                ('nivel_energia', models.IntegerField(choices=[(1, '🔴 Muy baja'), (2, '🟠 Baja'), (3, '🟡 Media'), (4, '🟢 Alta'), (5, '⭐ Excelente')])),
                ('nivel_concentracion', models.IntegerField(choices=[(1, '🔴 Muy baja'), (2, '🟠 Baja'), (3, '🟡 Media'), (4, '🟢 Alta'), (5, '⭐ Excelente')])),
                ('objetivos_cumplidos', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('interrupciones', models.IntegerField(default=0)),
                ('descansos_tomados', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyflow.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Estudio',
                'verbose_name_plural': 'Sesiones de Estudio',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
