# Generated by Django 5.2.2 on 2025-07-24 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0009_sesionestudio'),
    ]

    operations = [
    ]
