# Generated by Django 5.2.1 on 2025-07-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0009_sesionestudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
