# Generated by Django 5.2.2 on 2025-07-24 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0010_auto_20250723_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='periodo',
        ),
        migrations.AddField(
            model_name='gasto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('materiales', 'Materiales de Estudio'), ('libros', 'Libros'), ('tecnologia', 'Tecnología'), ('transporte', 'Transporte')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='periodo',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('semanal', 'Semanal')], max_length=10),
        ),
    ]
