# Generated by Django 5.2.2 on 2025-07-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0010_perfilusuario_foto_perfil_perfilusuario_pais'),
        ('studyflow', '0011_alter_gasto_options_remove_gasto_periodo_and_more'),
    ]

    operations = [
    ]
