# Generated by Django 5.2.1 on 2025-07-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0012_merge_20250723_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
